### ISSUE TITLE
Run successfully, but show nothing in web browser

### ISSUE THREAD

**Issue by tarvos21** [daogangtang/forustm2#1]
This is nothing shown at localhost:8081, in the command line it shows this erro:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Connection refused (os error 61)', src/libcore/result.rs:1084:5
```

What may be the problem? Thanks!

**Comment by miketang84** [comment]
Hi, pls see README.md file I just added, thanks for your testing.

**Comment by miketang84** [comment]
Your problem is that couldn't connect db.

**Comment by tarvos21** [comment]
Thanks, I got it.
