### ISSUE TITLE
POST /s/article/delete returns "article delete error"

### ISSUE THREAD

**Issue by tarvos21** [daogangtang/forustm2#11]
When I login as admin, I try to delete other user's article. But a POST to route `/s/article/delete` returns 'article delete error', do not find what caused the error.
The POST to delete comments works fine, but article does not work. 

What may be the problem?

**Comment by tarvos21** [comment]
Sometimes the admin can delete other user's article, but sometimes admin can not. I don't understand why there is a difference.

**Comment by miketang84** [comment]
I there are comments attached to that article, you cann't delete that article directly, unless you delete those comments first.

**Comment by tarvos21** [comment]
Oh, I see, thanks!
