### ISSUE TITLE
'login_with_admin' fails and needs to create user with register and login

### ISSUE THREAD

**Issue by tarvos21** [daogangtang/forustm2#2]
I go to the url 'login_with_admin', enter the admin account and password, but nothing happens?

And for local testing, how to create some users conveniently?

Thanks!

**Comment by miketang84** [comment]
Oh, sorry, I forgot to write the step of importing sql schema to db, let's do it.

**Comment by miketang84** [comment]
I, updated in README.md already.

Thanks for your response.

**Comment by tarvos21** [comment]
Thanks!

**Comment by tarvos21** [comment]
I run the `create_test_user.sh` script, but get `404 not found`? The url `/s/user/register` seems broken?

**Comment by miketang84** [comment]
ok, fix it. :)

**Comment by tarvos21** [comment]
thanks, it works!
but how to login? any way to add new user and login into the forum from the web browser?

**Comment by miketang84** [comment]
Hi, you can visit /login_with_admin, and use the created user just now:
account: mike
password: 123
to login.

Page name is confusing, but make sense.

And in the normal case, when run this forum in practical area, we advise to use github oauth to login, like https://rust.cc, and https://wasm-dev.org.

**Comment by tarvos21** [comment]
OK, I got the idea, thanks!
