### ISSUE TITLE
Webpage can not load when editing the view files

### ISSUE THREAD

**Issue by tarvos21** [daogangtang/forustm2#7]
When I edit the view files in my text editor(vim), I save the file(in the editor) but not exit the file, however, the webpage can not be loaded in the web browser.

I must exit the file from editor, then the webpages can show up.

What's the problem? Anyway to edit the file then checking the effects simultaneously?

**Comment by miketang84** [comment]
I don't know what, you can test it in vscode?

**Comment by tarvos21** [comment]
I guess I must save and close the view files to reload.
